#!/bin/bash

cd "$(dirname "$0")"

raw_day="$(echo "$1" | grep -o '[0-9]\+')"
day="$(printf "%02d\n" $raw_day)"

[ -d "$1" ] && exit

mkdir -p $1
cp -ar ./template/* ./$1/

# Solution
echo "require_relative \"../helpers/Solution\"

module Day$day" | cat - ./$1/Solution.rb > /tmp/out && mv /tmp/out ./$1/Solution.rb

# solve
echo "require_relative \"./Solution\"

DAY = \"$day\"
" | cat - ./$1/solve.rb > /tmp/out && mv /tmp/out ./$1/solve.rb
